   <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Navegaci&oacute;n</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand"><span class="glyphicon glyphicon-menu-hamburger"></span> Men&uacute;</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-globe"></span> Lugares<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="../guardar/guardar-pais.php" title="Guardar Pa&iacute;s"><span class="glyphicon glyphicon-flag"></span> Pa&iacute;s</a></li>
                <li><a href="../guardar/guardar-departamento.php" title="Guardar Departamento o Estado"><span class="glyphicon glyphicon-map-marker"></span> Departamento - Estado</a></li>
                <li><a href="../guardar/guardar-ciudad.php" title="Guardar Ciudad o Municipio"><span class="glyphicon glyphicon-stats"></span> Cuidad - Municipio</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="../guardar/guardar-temporada.php" title="Guardar Temporada"><span class="glyphicon glyphicon-cloud"></span> Temporada</a></li>
                <li><a href="../guardar/guardar-destino.php" title="Guardar Destino"><span class="glyphicon glyphicon-picture"></span> Destino</a></li>
                <li role="separator" class="divider"></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-briefcase"></span>Proveedor<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="../guardar/guardar-tipoproveedor.php" title="Guardar Tipo Proveedor"><span class="glyphicon glyphicon-list-alt"></span> Tipo Proveedor</a></li>
                <li><a href="../guardar/guardar-proveedor.php" title="Guardar Proveedor"><span class="glyphicon glyphicon-shopping-cart"></span> Proveedor</a></li>
                <li role="separator" class="divider"></li>
              </ul>
            </li> 
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-folder-open"></span> Cliente<b class="caret"></b></a>
              <ul class="dropdown-menu">
            <!--    <li><a href="../guardar/guardar-estadocliente.php" title="Ver Estados Del Cliente"><span class="glyphicon glyphicon-tags"></span> Estado Cliente</a></li> -->
                <li><a href="../guardar/guardar-tipovisa.php" title="Ver Tipos De Visa"><span class="glyphicon glyphicon-plane"></span> Tipo Visa</a></li>
            <!--       <li role="separator" class="divider"></li> -->
                <li><a href="../guardar/guardar-cliente.php" title="Guardar Cliente"><span class="glyphicon glyphicon-folder-close"></span> Cliente</a></li>
                <li role="separator" class="divider"></li>
              </ul>
            </li>
            <li><a href="../guardar/guardar-servicioturistico.php" ><span class="glyphicon glyphicon-gift"></span> Servicios</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-send"></span> <span class="glyphicon glyphicon-sunglasses"></span> Tours<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="../guardar/guardar-tour.php" title="Guardar Tours"><span class="glyphicon glyphicon-bed"></span> Tour</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="../guardar/guardar-itinerario.php" title="Guardar Itinerario"><span class="glyphicon glyphicon-time"></span> Itinerario</a></li>
                <li><a href="../guardar/guardar-serviciostour.php" title="Guardar Servicios De Un Tour"><span class="glyphicon glyphicon-list"></span> Servicios Del Tour</a></li>
                <li role="separator" class="divider"></li>
              </ul>
            </li>
            <li><a href="../guardar/guardar-reserva.php" ><span class="glyphicon glyphicon-usd"></span> Reservas</a></li>         
            <li><a href="../" onclick="return confirm('Confirmar: &iquest;Est&aacute; seguro que desea salir del Sistema?')"><span class="glyphicon glyphicon-share"></span> Salir</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>